# Generated by Django 4.0.6 on 2022-08-01 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
        ('calorie', '0005_note_delete_useraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('total_calories', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('category', models.CharField(choices=[('S', 'Snack'), ('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('C', 'Cheat Meal')], max_length=1)),
                ('date_eaten', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_api.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
